apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petclinic-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: petclinic
          servicePort: 8080
      - path: /actuator.*
        backend:
          serviceName: notfound-service
          servicePort: 8080
      - path: /actuator/health
        backend:
          serviceName: petclinic
          servicePort: 8080
      - path: /api/gateway/.*
        backend:
          serviceName: api-gateway
          servicePort: 8080
      - path: /api/customer/.*
        backend:
          serviceName: customers-service
          servicePort: 8080
      - path: /api/vet/.*
        backend:
          serviceName: vets-service
          servicePort: 8080
      - path: /api/visit/.*
        backend:
          serviceName: visits-service
          servicePort: 8080
